name: Deploy Dashboard

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Uploading the dashboard folder directly makes it the root of your site
          path: './src/dashboard'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4